### ISSUE TITLE
code information

### ISSUE THREAD

**Issue by kirthimanasa** [maaaaz/androwarn#13]
Can you please share us the structure of the code that is written for androwarn. I am trying to find malicous apk file but I am unable to run them with this tools.
Hoping to hear soon from you.

**Comment by maaaaz** [comment]
Hello, what do you mean by 'share the structure of code' ?

**Comment by kirthimanasa** [comment]
I am trying to understand the working of the tool. But, I couldn't
understand by looking at the code. So, can you please provide me a detailed
description of working of the tool i.e., the algorithms used and how is
that algorithm analyzing the features of a malicious mobile application.
And when I tried to give a downloaded apk file as input, it is generating
errors whereas it worked for other apk file which has been downloaded from
the same website i.e., apkpure.com. Can you please help me out with this.

Regards,
Manasa

**Comment by maaaaz** [comment]
You can find some information here: https://github.com/maaaaz/androwarn/wiki/Add-your-own-detection-criteria
