### ISSUE TITLE
ImportError: No module named androguard.misc

### ISSUE THREAD

**Issue by m2farah** [maaaaz/androwarn#18]
After installing the requirements. I start the program as explained in the Readme file. But I faced this error message : 
```
Traceback (most recent call last):
  File "androwarn.py", line 30, in <module>
    from androguard.misc import AnalyzeAPK
ImportError: No module named androguard.misc
```

**Comment by maaaaz** [comment]
Hello,

Have you installed the [dependencies](https://github.com/maaaaz/androwarn#dependencies-and-installation) ?
This error message shows that `androguard` is not installed.
