### ISSUE TITLE
Getting IndexError: list index out of range errors

### ISSUE THREAD

**Issue by StephenQuirolgico** [maaaaz/androwarn#2]
We are also getting "IndexError: list index out of range" errors but I cannot send the app for this.  We have also seen a "ValueError: invalid literal for int() with base 10: 'android.intent.action.PACKAGE_ADDED 11'" error but cannot find the app that generated this error.

**Comment by Josue198s** [comment]
I get the same issue, did you guys manage to get it sorted out?

**Comment by StephenQuirolgico** [comment]
I never solved it. Maaaaz never responded.

**Comment by maaaaz** [comment]
I fixed it along with https://github.com/maaaaz/androwarn/pull/7

Cheers.
