### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by StephenQuirolgico** [maaaaz/androwarn#22]
I got an error using Androwarn on the following Android app:

[https://play.google.com/store/apps/details?id=com.vaytek.crossfireremote](https://play.google.com/store/apps/details?id=com.vaytek.crossfireremote)

Note that I am using Python 2.7.

Traceback (most recent call last):
File "/data/androwarn/androwarn.py", line 116, in
main(options, arguments)
File "/data/androwarn/androwarn.py", line 95, in main
a, d, x = AnalyzeAPK(APK_FILE)
File "/data/androwarn/androwarn/analysis/analysis.py", line 48, in AnalyzeAPK
a = APK(filename, raw)
File "/data/androwarn/androguard/core/bytecodes/apk.py", line 163, in __init__
self.xml[i] = minidom.parseString( AXMLPrinter( self.zip.read( i ) ).getBuff() )
File "/data/androwarn/androguard/core/bytecodes/apk.py", line 877, in __init__
self.buff += "<%s%s\n" % ( self.getPrefix( self.axml.getPrefix() ), self.axml.getName() )
File "/data/androwarn/androguard/core/bytecodes/apk.py", line 749, in getName
return self.sb.getRaw(self.m_name)
File "/data/androwarn/androguard/core/bytecodes/apk.py", line 556, in getRaw
data += unichr( self.getShort(self.m_strings, offset) )
File "/data/androwarn/androguard/core/bytecodes/apk.py", line 567, in getShort
value = array[offset/4].get_value()
IndexError: list index out of range

**Comment by maaaaz** [comment]
Hello @StephenQuirolgico,

Sorry for the delay but I just ran successfully `androwarn` on this APK with Python 2 (and also Python 3).

Just refresh your dependency environment and try again:
```
$ pip uninstall -y androguard androwarn argparse future jinja2 play_scraper
$ pip install androwarn
$ pip freeze
pip freeze
androguard==3.3.5
androwarn==1.6.1
asn1crypto==0.24.0
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.1
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
colorama==0.4.1
cryptography==2.4.2
cycler==0.10.0
decorator==4.3.0
enum34==1.1.6
future==0.18.2
futures==3.2.0
idna==2.7
ipaddress==1.0.22
ipython==5.8.0
ipython-genutils==0.2.0
Jinja2==2.10.3
kiwisolver==1.0.1
lxml==4.3.0
MarkupSafe==1.1.0
matplotlib==2.2.3
networkx==2.2
numpy==1.15.4
pathlib2==2.3.3
pexpect==4.6.0
pickleshare==0.7.5
play-scraper==0.6.0
prompt-toolkit==1.0.15
ptyprocess==0.6.0
pycparser==2.19
pydot==1.4.1
Pygments==2.3.1
pyOpenSSL==18.0.0
pyparsing==2.3.0
python-dateutil==2.7.5
pytz==2018.7
requests==2.20.0
requests-futures==0.9.7
scandir==1.9.0
simplegeneric==0.8.1
six==1.12.0
subprocess32==3.5.3
traitlets==4.3.2
urllib3==1.24.1
wcwidth==0.1.7
```

Cheers.
