### ISSUE TITLE
Find replacement for chilkat

### ISSUE THREAD

**Issue by dpquigl** [maaaaz/androwarn#4]
The dependency on chilkat is really a pain. Its a swig wrapper around a closed source binary and it requires a license to use for more than 30 days.

**Comment by maaaaz** [comment]
Hello there,

For your information from version 1.1 there's no `chilkat` dependencies anymore, `androwarn` is now using `asn1crypto` module for this purpose, such as [documented here](https://androguard.readthedocs.io/en/latest/intro/certificates.html)

Cheers
